FROM node:23.6-alpine3.21 AS base
RUN npm i -g yarn --force

# development stage
FROM base AS development
WORKDIR /opt/api
EXPOSE 5000
ENTRYPOINT ["/bin/sh", "-c" , "yarn install -D && yarn dev"]

# build stage
FROM base AS build
WORKDIR /opt/api
COPY . .
RUN yarn install
RUN yarn build

# production stage
FROM nginx:1.27.1-alpine3.21 AS production

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /api/dist /opt/app

EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]
